spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yunxiai88/spring-boot-samples.git
          search-paths: config-repo
          username: nx88
          password: admin 
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8000/eureka/

---
spring:
  profiles: default
server:
  port: 8020

---
spring:
  profiles: node1
server:
  port: 8021
