spring:
    application:
        name: spring-cloud-consumer

    cloud:
        loadbalancer:
            ribbon:
                enabled: false

server:
    port: 8011

feign:
    hystrix:
        enabled: true

management:
    endpoints:
        web:
            exposure:
                include: "*"

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://localhost:8000/eureka/
