server:
  port: 8030

spring:
  application:
    name: spring-cloud-config-client
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
